In [171]:
import numpy as np
import pandas as pd
from bokeh.plotting import figure, output_file, show
from bokeh.layouts import gridplot
from bokeh.models import ColumnDataSource
from bokeh.charts import Histogram

In [88]:
output_file = 'test.html' #defines an output file for any graph

In [89]:
main_df = pd.read_csv('starcraft_player_list.csv')

In [90]:
main_df.pop('Unnamed: 0')

0        0
1        1
2        2
3        3
4        4
5        5
6        6
7        7
8        8
9        9
10      10
11      11
12      12
13      13
14      14
15      15
16      16
17      17
18      18
19      19
20      20
21      21
22      22
23      23
24      24
25      25
26      26
27      27
28      28
29      29
        ..
1653    53
1654    54
1655    55
1656    56
1657    57
1658    58
1659    59
1660    60
1661    61
1662    62
1663    63
1664    64
1665    65
1666    66
1667    67
1668    68
1669    69
1670    70
1671    71
1672    72
1673    73
1674    74
1675    75
1676    76
1677    77
1678    78
1679    79
1680    80
1681    81
1682    82
Name: Unnamed: 0, Length: 1683, dtype: int64

In [12]:
main_df

,CountryCode,CurrentHandle,NameFirst,NameLast,PlayerId,TotalUSDPrize
0,kr,MC,Min Chul,Jang,1000,506645.42
1,kr,sOs,Yoo Jin,Kim,2272,497206.27
2,kr,Life,Seung Hyun,Lee,1429,475900.67
3,kr,Polt,Sung Hoon,Choi,1003,451599.10
4,kr,INnoVation,Shin Hyung,Lee,2268,441857.09
5,kr,TY,Tae Yang,Jun,2224,440814.52
6,kr,Mvp,Jong Hyun,Jung,1002,404265.42
7,kr,MMA,Sung Won,Moon,1007,395456.54
8,kr,Byun,Hyun Woo,Byun,1017,389971.93
9,kr,PartinG,Lee Sak,Won,1132,355604.37
10,no,Snute,Jens,Aasgaard,1257,334526.98
11,kr,Zest,Sung Wook,Joo,4674,331634.91
12,kr,Maru,Sung Choo,Cho,1126,318353.50
13,pl,Nerchio,Artur,Bloch,1227,298026.03
14,kr,NesTea,Jae Duk,Lim,1001,287702.13
15,kr,TaeJa,Young Suh,Yoon,1061,284752.52
16,fr,Stephano,Ilyes,Satouri,1158,282466.02
17,kr,Dark,Ryung Woo,Park,3620,278852.29
18,kr,Leenock,Dong Nyung,Lee,1025,266543.13
19,kr,HerO,Hyeon Deok,Song,1086,264105.72
20,kr,DongRaeGu,Soo Ho,Park,1057,259858.98
21,kr,Bomber,Ji Sung,Choi,1030,256952.14
22,us,Neeb,Alex,Sunderhaft,3818,256733.50
23,kr,Stats,Dae Yeob,Kim,2236,244974.71
24,kr,Rain,Yoon Jong,Jung,3041,239358.36
25,kr,HyuN,Seok Hyun,Ko,1426,233413.60
26,kr,Classic,Doh Woo,Kim,2271,232901.18
27,kr,Jaedong,Jae Dong,Lee,1507,224833.53
28,kr,Solar,Min Soo,Kang,3657,221149.57
29,kr,herO,Joon Ho,Kim,3042,217695.24
...,...,...,...,...,...,...
1653,us,Sacrilege,Austin,Fiorito,25323,15.00
1654,us,Qualia,-,-,27238,15.00
1655,us,roka,-,-,31366,15.00
1656,bg,ArchangeL,-,-,32094,15.00
1657,us,Towelie,Ryan,Pannell,32095,15.00
1658,us,LiqhT,Kailash,Jayaram,32096,15.00
1659,us,Operator,-,-,34657,15.00
1660,pl,ToZiS,-,-,40763,13.89
1661,de,Miezekotze,-,-,35644,13.47
1662,gb,AsTeR,Connor,Richardson,21368,13.32
1663,gb,Genesis,-,-,26807,12.50
1664,us,Resolve,-,-,26808,12.50
1665,us,LOOPY,-,-,31247,12.50
1666,ua,Hades,Aleksei,Chistiakov,34099,12.47
1667,vn,Beethoven,-,-,7324,10.72
1668,nz,MaSteR,Do Young,Kim,7323,10.53
1669,au,EdgE,Cameron,Murrin,7321,10.15
1670,ru,OvermindMK,Mihail,Krotov,34101,10.10
1671,ru,Fallenger,Vladimir,Zolnov,34104,10.10
1672,es,AqueroN,Rubén,Villanueva,22861,10.00
1673,us,CalebAracous,Caleb,Jones,27260,10.00
1674,ve,ThuNdeR,Jorge,Zambrano,28593,7.14
1675,ve,Demonizer,Guillermo,Lunar,28594,7.14
1676,pe,Kuyzz,-,-,28595,7.14
1677,ru,Sunokasuri,-,-,35645,6.74
1678,at,Sylvanas,Chantal,Frey,35646,3.37
1679,us,NoveaStar,-,-,35647,3.37
1680,us,Poizon,-,-,35648,3.37
1681,be,Anolia,-,-,35649,3.37
1682,ru,Easy,-,-,38984,2.37

In [91]:
tourney = pd.read_csv('tourney.csv')

In [94]:
tourney.pop('Unnamed: 0')

0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
         ..
23686    35
23687    36
23688    37
23689    38
23690    39
23691    40
23692    41
23693    42
23694    43
23695    44
23696    45
23697    46
23698    47
23699    48
23700    49
23701    50
23702    51
23703    52
23704    53
23705    54
23706    55
23707    56
23708    57
23709    58
23710    59
23711    60
23712    61
23713    62
23714    63
23715    64
Name: Unnamed: 0, Length: 23716, dtype: int64

In [95]:
tourney

,CurrencyCode,EndDate,ExchangeRate,GameId,Note,Prize,RankText,TeamPlayers,TournamentName,PlayerId
0,KRW,2016-09-10,0.000905,151,NaN,3000000.0,17th-24th,1,GSL Season 2 2016 (Code S),1000
1,USD,2016-02-02,1.000000,151,NaN,1000.0,5th-8th,1,IEM X - Taipei (SC2),1000
2,USD,2015-12-20,1.000000,151,NaN,875.0,5th-8th,1,HomeStory Cup XII,1000
3,USD,2015-12-12,1.000000,151,NaN,600.0,2nd,1,WW3,1000
4,USD,2015-12-01,1.000000,151,NaN,100.0,WIN,1,Showmatch MC vs. TLO,1000
5,USD,2015-09-19,1.000000,151,NaN,15000.0,1st,2,Red Bull Battle Grounds - Washington 2015 (Arc...,1000
6,USD,2015-08-30,1.000000,151,NaN,2490.0,2nd,2,Red Bull Battle Grounds - Santa Monica 2015 (A...,1000
7,KRW,2015-04-17,0.000914,151,NaN,400000.0,25th-48th,1,GSL Season 2 2015 (Code A),1000
8,KRW,2015-03-22,0.000898,151,NaN,1500000.0,13th-16th,1,2015 Global StarCraft II League Season 1,1000
9,USD,2014-11-08,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2014 Global Finals,1000
10,USD,2014-10-05,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 3 Premier,1000
11,USD,2014-10-03,1.000000,151,NaN,800.0,4th,1,Connecting Professional E-sports #1,1000
12,USD,2014-09-30,1.000000,151,NaN,3500.0,WIN,3,NationWars II - Korea vs. Norway,1000
13,USD,2014-08-31,1.000000,151,NaN,400.0,9th-12th,1,IEM IX - Toronto (StarCraft II),1000
14,USD,2014-08-03,1.000000,151,NaN,3000.0,3rd-4th,1,Gfinity G3 (Starcraft II),1000
15,USD,2014-07-20,1.000000,151,NaN,5000.0,2nd,1,DreamHack Valencia 2014 (SC2),1000
16,USD,2014-07-06,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 2 Premier,1000
17,EUR,2014-06-22,1.359912,151,NaN,50.0,2nd,1,Go4SC2 EU #381,1000
18,USD,2014-06-16,1.000000,151,NaN,1000.0,7th-8th,1,DreamHack Summer 2014 (StarCraft II),1000
19,USD,2014-06-08,1.000000,151,NaN,6500.0,2nd,1,HomeStory Cup IX,1000
20,USD,2014-04-27,1.000000,151,NaN,1000.0,5th-8th,1,DreamHack Bucharest 2014 (StarCraft II),1000
21,EUR,2014-04-20,1.380905,151,NaN,100.0,1st,1,Go4SC2 EU #363,1000
22,USD,2014-04-13,1.000000,151,NaN,25000.0,1st,1,WCS Europe 2014 Season 1 Premier,1000
23,USD,2014-02-16,1.000000,151,NaN,400.0,9th-12th,1,IEM VIII - Cologne (StarCraft II),1000
24,USD,2014-02-07,1.000000,151,NaN,3000.0,1st,1,Warer.com Invitational,1000
25,USD,2014-02-01,1.000000,151,NaN,4000.0,2nd,1,IEM VIII - Sao Paulo (StarCraft II),1000
26,SEK,2013-12-09,0.153017,151,NaN,8000.0,4th,1,Fragbite Masters 2013 (StarCraft II),1000
27,USD,2013-11-24,1.000000,151,NaN,4000.0,4th,1,Red Bull Battle Grounds: Grand Finals New York...,1000
28,USD,2013-11-09,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2013 Global Finals,1000
29,USD,2013-10-27,1.000000,151,NaN,7500.0,5th-8th,1,WCS 2013 Season 3 Finals,1000
...,...,...,...,...,...,...,...,...,...,...
23686,EUR,2013-01-22,1.282848,151,NaN,500.0,WIN,1,Go4SC2 November 2012 Monthly Finals,1257
23687,USD,2013-01-20,1.000000,151,NaN,650.0,17th-20th,1,IEM VII - Katowice (StarCraft II),1257
23688,USD,2012-12-22,1.000000,151,NaN,10000.0,1st,1,HomeStory Cup VI,1257
23689,EUR,2012-12-16,1.311272,151,NaN,200.0,WIN,1,Go4SC2 EU #252,1257
23690,USD,2012-12-16,1.000000,151,NaN,1000.0,3rd,1,PokerStrategy.com League,1257
23691,SEK,2012-12-09,0.149689,151,NaN,30000.0,2nd,1,THOR Open 2012 (Starcraft II),1257
23692,USD,2012-12-02,1.000000,151,NaN,500.0,13th-16th,1,IGN Pro League Season 5 (Starcraft II),1257
23693,EUR,2012-11-27,1.271412,151,NaN,450.0,1st,1,GameCreds Invitational,1257
23694,SEK,2012-11-24,0.150917,151,NaN,25000.0,5th-8th,1,DreamHack Winter 2012 (StarCraft II),1257
23695,EUR,2012-11-16,1.271412,151,NaN,1000.0,2nd,1,Acer StarCraft Challenge,1257
23696,EUR,2012-11-04,1.282848,151,NaN,200.0,WIN,1,Go4SC2 EU #241,1257
23697,USD,2012-09-28,1.000000,151,NaN,300.0,WIN,1,BO69 FXOBabyKnight vs GLSnute Showmatch,1257
23698,EUR,2012-09-13,1.299350,151,NaN,200.0,3rd,1,GIGABYTE NVIDIA Invitational #4,1257
23699,USD,2012-09-02,1.000000,151,NaN,800.0,3rd,1,Battle at Ministry of Win: get outPlayed,1257
23700,USD,2012-08-25,1.000000,151,NaN,3000.0,2nd,1,Campus Party: Europe in Berlin (Starcraft II),1257
23701,USD,2012-07-28,1.000000,151,NaN,350.0,4th,1,WCS 2012: Norway,1257
23702,EUR,2012-07-18,1.226227,151,NaN,75.0,2nd,1,Antec Attack #25,1257
23703,EUR,2012-07-16,1.226548,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #65,1257
23704,EUR,2012-04-16,1.306836,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #54,1257
23705,USD,2012-04-01,1.000000,151,NaN,2000.0,1st,1,ONOG i2 Starcraft 2 Invitational,1257
23706,EUR,2012-03-29,1.320784,151,NaN,250.0,1st,1,4PL Close Combat Cup 2012 March Finals,1257
23707,EUR,2012-03-08,1.320784,151,NaN,50.0,WIN,1,4PL Close Combat Cup 2012 March Qualifier #3,1257
23708,NOK,2012-02-24,0.179566,151,NaN,20000.0,1st,1,Nemean LAN 2012,1257
23709,USD,2012-02-11,1.000000,151,NaN,650.0,9th-12th,1,IEM VI - Sao Paulo (StarCraft II),1257
23710,EUR,2011-11-28,1.333371,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #41,1257
23711,NOK,2011-10-08,0.171574,151,NaN,20000.0,1st,1,Polar Party 20 (StarCraft II),1257
23712,EUR,2011-06-13,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #50,1257
23713,EUR,2011-06-09,1.439143,151,NaN,50.0,2nd,1,4PL Close Combat Cup 2011 #49,1257
23714,EUR,2011-06-06,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #48,1257
23715,EUR,2011-05-16,1.431440,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #42,1257

In [96]:
tourney['Prize_USD'] = tourney['Prize']*tourney['ExchangeRate']

In [97]:
touruniq = tourney.drop_duplicates()

In [98]:
touruniq

,CurrencyCode,EndDate,ExchangeRate,GameId,Note,Prize,RankText,TeamPlayers,TournamentName,PlayerId,Prize_USD
0,KRW,2016-09-10,0.000905,151,NaN,3000000.0,17th-24th,1,GSL Season 2 2016 (Code S),1000,2714.195100
1,USD,2016-02-02,1.000000,151,NaN,1000.0,5th-8th,1,IEM X - Taipei (SC2),1000,1000.000000
2,USD,2015-12-20,1.000000,151,NaN,875.0,5th-8th,1,HomeStory Cup XII,1000,875.000000
3,USD,2015-12-12,1.000000,151,NaN,600.0,2nd,1,WW3,1000,600.000000
4,USD,2015-12-01,1.000000,151,NaN,100.0,WIN,1,Showmatch MC vs. TLO,1000,100.000000
5,USD,2015-09-19,1.000000,151,NaN,15000.0,1st,2,Red Bull Battle Grounds - Washington 2015 (Arc...,1000,15000.000000
6,USD,2015-08-30,1.000000,151,NaN,2490.0,2nd,2,Red Bull Battle Grounds - Santa Monica 2015 (A...,1000,2490.000000
7,KRW,2015-04-17,0.000914,151,NaN,400000.0,25th-48th,1,GSL Season 2 2015 (Code A),1000,365.600000
8,KRW,2015-03-22,0.000898,151,NaN,1500000.0,13th-16th,1,2015 Global StarCraft II League Season 1,1000,1346.825550
9,USD,2014-11-08,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2014 Global Finals,1000,5000.000000
10,USD,2014-10-05,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 3 Premier,1000,5000.000000
11,USD,2014-10-03,1.000000,151,NaN,800.0,4th,1,Connecting Professional E-sports #1,1000,800.000000
12,USD,2014-09-30,1.000000,151,NaN,3500.0,WIN,3,NationWars II - Korea vs. Norway,1000,3500.000000
13,USD,2014-08-31,1.000000,151,NaN,400.0,9th-12th,1,IEM IX - Toronto (StarCraft II),1000,400.000000
14,USD,2014-08-03,1.000000,151,NaN,3000.0,3rd-4th,1,Gfinity G3 (Starcraft II),1000,3000.000000
15,USD,2014-07-20,1.000000,151,NaN,5000.0,2nd,1,DreamHack Valencia 2014 (SC2),1000,5000.000000
16,USD,2014-07-06,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 2 Premier,1000,5000.000000
17,EUR,2014-06-22,1.359912,151,NaN,50.0,2nd,1,Go4SC2 EU #381,1000,67.995600
18,USD,2014-06-16,1.000000,151,NaN,1000.0,7th-8th,1,DreamHack Summer 2014 (StarCraft II),1000,1000.000000
19,USD,2014-06-08,1.000000,151,NaN,6500.0,2nd,1,HomeStory Cup IX,1000,6500.000000
20,USD,2014-04-27,1.000000,151,NaN,1000.0,5th-8th,1,DreamHack Bucharest 2014 (StarCraft II),1000,1000.000000
21,EUR,2014-04-20,1.380905,151,NaN,100.0,1st,1,Go4SC2 EU #363,1000,138.090500
22,USD,2014-04-13,1.000000,151,NaN,25000.0,1st,1,WCS Europe 2014 Season 1 Premier,1000,25000.000000
23,USD,2014-02-16,1.000000,151,NaN,400.0,9th-12th,1,IEM VIII - Cologne (StarCraft II),1000,400.000000
24,USD,2014-02-07,1.000000,151,NaN,3000.0,1st,1,Warer.com Invitational,1000,3000.000000
25,USD,2014-02-01,1.000000,151,NaN,4000.0,2nd,1,IEM VIII - Sao Paulo (StarCraft II),1000,4000.000000
26,SEK,2013-12-09,0.153017,151,NaN,8000.0,4th,1,Fragbite Masters 2013 (StarCraft II),1000,1224.139528
27,USD,2013-11-24,1.000000,151,NaN,4000.0,4th,1,Red Bull Battle Grounds: Grand Finals New York...,1000,4000.000000
28,USD,2013-11-09,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2013 Global Finals,1000,5000.000000
29,USD,2013-10-27,1.000000,151,NaN,7500.0,5th-8th,1,WCS 2013 Season 3 Finals,1000,7500.000000
...,...,...,...,...,...,...,...,...,...,...,...
23686,EUR,2013-01-22,1.282848,151,NaN,500.0,WIN,1,Go4SC2 November 2012 Monthly Finals,1257,641.424000
23687,USD,2013-01-20,1.000000,151,NaN,650.0,17th-20th,1,IEM VII - Katowice (StarCraft II),1257,650.000000
23688,USD,2012-12-22,1.000000,151,NaN,10000.0,1st,1,HomeStory Cup VI,1257,10000.000000
23689,EUR,2012-12-16,1.311272,151,NaN,200.0,WIN,1,Go4SC2 EU #252,1257,262.254400
23690,USD,2012-12-16,1.000000,151,NaN,1000.0,3rd,1,PokerStrategy.com League,1257,1000.000000
23691,SEK,2012-12-09,0.149689,151,NaN,30000.0,2nd,1,THOR Open 2012 (Starcraft II),1257,4490.681835
23692,USD,2012-12-02,1.000000,151,NaN,500.0,13th-16th,1,IGN Pro League Season 5 (Starcraft II),1257,500.000000
23693,EUR,2012-11-27,1.271412,151,NaN,450.0,1st,1,GameCreds Invitational,1257,572.135417
23694,SEK,2012-11-24,0.150917,151,NaN,25000.0,5th-8th,1,DreamHack Winter 2012 (StarCraft II),1257,3772.929982
23695,EUR,2012-11-16,1.271412,151,NaN,1000.0,2nd,1,Acer StarCraft Challenge,1257,1271.412038
23696,EUR,2012-11-04,1.282848,151,NaN,200.0,WIN,1,Go4SC2 EU #241,1257,256.569600
23697,USD,2012-09-28,1.000000,151,NaN,300.0,WIN,1,BO69 FXOBabyKnight vs GLSnute Showmatch,1257,300.000000
23698,EUR,2012-09-13,1.299350,151,NaN,200.0,3rd,1,GIGABYTE NVIDIA Invitational #4,1257,259.870000
23699,USD,2012-09-02,1.000000,151,NaN,800.0,3rd,1,Battle at Ministry of Win: get outPlayed,1257,800.000000
23700,USD,2012-08-25,1.000000,151,NaN,3000.0,2nd,1,Campus Party: Europe in Berlin (Starcraft II),1257,3000.000000
23701,USD,2012-07-28,1.000000,151,NaN,350.0,4th,1,WCS 2012: Norway,1257,350.000000
23702,EUR,2012-07-18,1.226227,151,NaN,75.0,2nd,1,Antec Attack #25,1257,91.967023
23703,EUR,2012-07-16,1.226548,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #65,1257,122.654847
23704,EUR,2012-04-16,1.306836,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #54,1257,130.683619
23705,USD,2012-04-01,1.000000,151,NaN,2000.0,1st,1,ONOG i2 Starcraft 2 Invitational,1257,2000.000000
23706,EUR,2012-03-29,1.320784,151,NaN,250.0,1st,1,4PL Close Combat Cup 2012 March Finals,1257,330.196000
23707,EUR,2012-03-08,1.320784,151,NaN,50.0,WIN,1,4PL Close Combat Cup 2012 March Qualifier #3,1257,66.039200
23708,NOK,2012-02-24,0.179566,151,NaN,20000.0,1st,1,Nemean LAN 2012,1257,3591.314674
23709,USD,2012-02-11,1.000000,151,NaN,650.0,9th-12th,1,IEM VI - Sao Paulo (StarCraft II),1257,650.000000
23710,EUR,2011-11-28,1.333371,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #41,1257,133.337075
23711,NOK,2011-10-08,0.171574,151,NaN,20000.0,1st,1,Polar Party 20 (StarCraft II),1257,3431.473474
23712,EUR,2011-06-13,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #50,1257,71.957150
23713,EUR,2011-06-09,1.439143,151,NaN,50.0,2nd,1,4PL Close Combat Cup 2011 #49,1257,71.957150
23714,EUR,2011-06-06,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #48,1257,71.957150
23715,EUR,2011-05-16,1.431440,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #42,1257,71.572000

In [99]:
df_mrg = pd.merge(touruniq, main_df, on='PlayerId')

In [100]:
df_mrg

,CurrencyCode,EndDate,ExchangeRate,GameId,Note,Prize,RankText,TeamPlayers,TournamentName,PlayerId,Prize_USD,CountryCode,CurrentHandle,NameFirst,NameLast,TotalUSDPrize
0,KRW,2016-09-10,0.000905,151,NaN,3000000.0,17th-24th,1,GSL Season 2 2016 (Code S),1000,2714.195100,kr,MC,Min Chul,Jang,506645.42
1,USD,2016-02-02,1.000000,151,NaN,1000.0,5th-8th,1,IEM X - Taipei (SC2),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42
2,USD,2015-12-20,1.000000,151,NaN,875.0,5th-8th,1,HomeStory Cup XII,1000,875.000000,kr,MC,Min Chul,Jang,506645.42
3,USD,2015-12-12,1.000000,151,NaN,600.0,2nd,1,WW3,1000,600.000000,kr,MC,Min Chul,Jang,506645.42
4,USD,2015-12-01,1.000000,151,NaN,100.0,WIN,1,Showmatch MC vs. TLO,1000,100.000000,kr,MC,Min Chul,Jang,506645.42
5,USD,2015-09-19,1.000000,151,NaN,15000.0,1st,2,Red Bull Battle Grounds - Washington 2015 (Arc...,1000,15000.000000,kr,MC,Min Chul,Jang,506645.42
6,USD,2015-08-30,1.000000,151,NaN,2490.0,2nd,2,Red Bull Battle Grounds - Santa Monica 2015 (A...,1000,2490.000000,kr,MC,Min Chul,Jang,506645.42
7,KRW,2015-04-17,0.000914,151,NaN,400000.0,25th-48th,1,GSL Season 2 2015 (Code A),1000,365.600000,kr,MC,Min Chul,Jang,506645.42
8,KRW,2015-03-22,0.000898,151,NaN,1500000.0,13th-16th,1,2015 Global StarCraft II League Season 1,1000,1346.825550,kr,MC,Min Chul,Jang,506645.42
9,USD,2014-11-08,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2014 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42
10,USD,2014-10-05,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 3 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42
11,USD,2014-10-03,1.000000,151,NaN,800.0,4th,1,Connecting Professional E-sports #1,1000,800.000000,kr,MC,Min Chul,Jang,506645.42
12,USD,2014-09-30,1.000000,151,NaN,3500.0,WIN,3,NationWars II - Korea vs. Norway,1000,3500.000000,kr,MC,Min Chul,Jang,506645.42
13,USD,2014-08-31,1.000000,151,NaN,400.0,9th-12th,1,IEM IX - Toronto (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42
14,USD,2014-08-03,1.000000,151,NaN,3000.0,3rd-4th,1,Gfinity G3 (Starcraft II),1000,3000.000000,kr,MC,Min Chul,Jang,506645.42
15,USD,2014-07-20,1.000000,151,NaN,5000.0,2nd,1,DreamHack Valencia 2014 (SC2),1000,5000.000000,kr,MC,Min Chul,Jang,506645.42
16,USD,2014-07-06,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 2 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42
17,EUR,2014-06-22,1.359912,151,NaN,50.0,2nd,1,Go4SC2 EU #381,1000,67.995600,kr,MC,Min Chul,Jang,506645.42
18,USD,2014-06-16,1.000000,151,NaN,1000.0,7th-8th,1,DreamHack Summer 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42
19,USD,2014-06-08,1.000000,151,NaN,6500.0,2nd,1,HomeStory Cup IX,1000,6500.000000,kr,MC,Min Chul,Jang,506645.42
20,USD,2014-04-27,1.000000,151,NaN,1000.0,5th-8th,1,DreamHack Bucharest 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42
21,EUR,2014-04-20,1.380905,151,NaN,100.0,1st,1,Go4SC2 EU #363,1000,138.090500,kr,MC,Min Chul,Jang,506645.42
22,USD,2014-04-13,1.000000,151,NaN,25000.0,1st,1,WCS Europe 2014 Season 1 Premier,1000,25000.000000,kr,MC,Min Chul,Jang,506645.42
23,USD,2014-02-16,1.000000,151,NaN,400.0,9th-12th,1,IEM VIII - Cologne (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42
24,USD,2014-02-07,1.000000,151,NaN,3000.0,1st,1,Warer.com Invitational,1000,3000.000000,kr,MC,Min Chul,Jang,506645.42
25,USD,2014-02-01,1.000000,151,NaN,4000.0,2nd,1,IEM VIII - Sao Paulo (StarCraft II),1000,4000.000000,kr,MC,Min Chul,Jang,506645.42
26,SEK,2013-12-09,0.153017,151,NaN,8000.0,4th,1,Fragbite Masters 2013 (StarCraft II),1000,1224.139528,kr,MC,Min Chul,Jang,506645.42
27,USD,2013-11-24,1.000000,151,NaN,4000.0,4th,1,Red Bull Battle Grounds: Grand Finals New York...,1000,4000.000000,kr,MC,Min Chul,Jang,506645.42
28,USD,2013-11-09,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2013 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42
29,USD,2013-10-27,1.000000,151,NaN,7500.0,5th-8th,1,WCS 2013 Season 3 Finals,1000,7500.000000,kr,MC,Min Chul,Jang,506645.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23057,EUR,2013-01-22,1.282848,151,NaN,500.0,WIN,1,Go4SC2 November 2012 Monthly Finals,1257,641.424000,no,Snute,Jens,Aasgaard,334526.98
23058,USD,2013-01-20,1.000000,151,NaN,650.0,17th-20th,1,IEM VII - Katowice (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98
23059,USD,2012-12-22,1.000000,151,NaN,10000.0,1st,1,HomeStory Cup VI,1257,10000.000000,no,Snute,Jens,Aasgaard,334526.98
23060,EUR,2012-12-16,1.311272,151,NaN,200.0,WIN,1,Go4SC2 EU #252,1257,262.254400,no,Snute,Jens,Aasgaard,334526.98
23061,USD,2012-12-16,1.000000,151,NaN,1000.0,3rd,1,PokerStrategy.com League,1257,1000.000000,no,Snute,Jens,Aasgaard,334526.98
23062,SEK,2012-12-09,0.149689,151,NaN,30000.0,2nd,1,THOR Open 2012 (Starcraft II),1257,4490.681835,no,Snute,Jens,Aasgaard,334526.98
23063,USD,2012-12-02,1.000000,151,NaN,500.0,13th-16th,1,IGN Pro League Season 5 (Starcraft II),1257,500.000000,no,Snute,Jens,Aasgaard,334526.98
23064,EUR,2012-11-27,1.271412,151,NaN,450.0,1st,1,GameCreds Invitational,1257,572.135417,no,Snute,Jens,Aasgaard,334526.98
23065,SEK,2012-11-24,0.150917,151,NaN,25000.0,5th-8th,1,DreamHack Winter 2012 (StarCraft II),1257,3772.929982,no,Snute,Jens,Aasgaard,334526.98
23066,EUR,2012-11-16,1.271412,151,NaN,1000.0,2nd,1,Acer StarCraft Challenge,1257,1271.412038,no,Snute,Jens,Aasgaard,334526.98
23067,EUR,2012-11-04,1.282848,151,NaN,200.0,WIN,1,Go4SC2 EU #241,1257,256.569600,no,Snute,Jens,Aasgaard,334526.98
23068,USD,2012-09-28,1.000000,151,NaN,300.0,WIN,1,BO69 FXOBabyKnight vs GLSnute Showmatch,1257,300.000000,no,Snute,Jens,Aasgaard,334526.98
23069,EUR,2012-09-13,1.299350,151,NaN,200.0,3rd,1,GIGABYTE NVIDIA Invitational #4,1257,259.870000,no,Snute,Jens,Aasgaard,334526.98
23070,USD,2012-09-02,1.000000,151,NaN,800.0,3rd,1,Battle at Ministry of Win: get outPlayed,1257,800.000000,no,Snute,Jens,Aasgaard,334526.98
23071,USD,2012-08-25,1.000000,151,NaN,3000.0,2nd,1,Campus Party: Europe in Berlin (Starcraft II),1257,3000.000000,no,Snute,Jens,Aasgaard,334526.98
23072,USD,2012-07-28,1.000000,151,NaN,350.0,4th,1,WCS 2012: Norway,1257,350.000000,no,Snute,Jens,Aasgaard,334526.98
23073,EUR,2012-07-18,1.226227,151,NaN,75.0,2nd,1,Antec Attack #25,1257,91.967023,no,Snute,Jens,Aasgaard,334526.98
23074,EUR,2012-07-16,1.226548,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #65,1257,122.654847,no,Snute,Jens,Aasgaard,334526.98
23075,EUR,2012-04-16,1.306836,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #54,1257,130.683619,no,Snute,Jens,Aasgaard,334526.98
23076,USD,2012-04-01,1.000000,151,NaN,2000.0,1st,1,ONOG i2 Starcraft 2 Invitational,1257,2000.000000,no,Snute,Jens,Aasgaard,334526.98
23077,EUR,2012-03-29,1.320784,151,NaN,250.0,1st,1,4PL Close Combat Cup 2012 March Finals,1257,330.196000,no,Snute,Jens,Aasgaard,334526.98
23078,EUR,2012-03-08,1.320784,151,NaN,50.0,WIN,1,4PL Close Combat Cup 2012 March Qualifier #3,1257,66.039200,no,Snute,Jens,Aasgaard,334526.98
23079,NOK,2012-02-24,0.179566,151,NaN,20000.0,1st,1,Nemean LAN 2012,1257,3591.314674,no,Snute,Jens,Aasgaard,334526.98
23080,USD,2012-02-11,1.000000,151,NaN,650.0,9th-12th,1,IEM VI - Sao Paulo (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98
23081,EUR,2011-11-28,1.333371,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #41,1257,133.337075,no,Snute,Jens,Aasgaard,334526.98
23082,NOK,2011-10-08,0.171574,151,NaN,20000.0,1st,1,Polar Party 20 (StarCraft II),1257,3431.473474,no,Snute,Jens,Aasgaard,334526.98
23083,EUR,2011-06-13,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #50,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98
23084,EUR,2011-06-09,1.439143,151,NaN,50.0,2nd,1,4PL Close Combat Cup 2011 #49,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98
23085,EUR,2011-06-06,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #48,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98
23086,EUR,2011-05-16,1.431440,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #42,1257,71.572000,no,Snute,Jens,Aasgaard,334526.98

In [101]:
df_mrg.GameId.unique()

array([151, 152, 158, 426, 328, 371, 231, 225, 242, 163, 164, 179, 178,
       165, 347, 245, 504, 162, 483, 433, 272, 172, 345, 204, 364])

In [102]:
df_sc2 = df_mrg[df_mrg.GameId==151]

In [103]:
df_notsc2 = df_mrg[df_mrg.GameId!=151]

In [104]:
df_notsc2

,CurrencyCode,EndDate,ExchangeRate,GameId,Note,Prize,RankText,TeamPlayers,TournamentName,PlayerId,Prize_USD,CountryCode,CurrentHandle,NameFirst,NameLast,TotalUSDPrize
108,KRW,2009-08-22,0.000803,152,NaN,100000.0,3rd,1,Bacchus OSL 2009 (Ro36),1000,80.269700,kr,MC,Min Chul,Jang,506645.42
165,KRW,2011-02-19,0.000901,152,NaN,500000.0,17th-32nd,1,PDPop MSL 2010,2272,450.450450,kr,sOs,Yoo Jin,Kim,497206.27
492,KRW,2012-08-04,0.000881,152,NaN,2000000.0,9th-16th,1,Tving OSL 2012,2268,1762.192000,kr,INnoVation,Shin Hyung,Lee,441857.09
493,KRW,2010-01-23,0.000868,152,NaN,2000000.0,9th-16th,1,NATE MSL 2009,2268,1735.508400,kr,INnoVation,Shin Hyung,Lee,441857.09
542,KRW,2011-09-17,0.000900,152,NaN,2000000.0,9th-16th,1,Jin Air OSL 2011,2224,1799.775000,kr,TY,Tae Yang,Jun,440814.52
543,KRW,2011-01-29,0.000897,152,NaN,150000.0,2nd,1,Bacchus OSL 2010 (Ro36),2224,134.505015,kr,TY,Tae Yang,Jun,440814.52
544,KRW,2010-09-11,0.000858,152,NaN,150000.0,2nd,1,Korean Air OSL #2 2010 (Ro36),2224,128.755365,kr,TY,Tae Yang,Jun,440814.52
545,KRW,2010-05-29,0.000837,152,NaN,2000000.0,9th-16th,1,Hana Daetoo MSL 2010,2224,1674.200600,kr,TY,Tae Yang,Jun,440814.52
546,KRW,2010-05-22,0.000838,152,NaN,3000000.0,5th-8th,1,Korean Air OSL #1 2010 (Playoffs),2224,2514.458100,kr,TY,Tae Yang,Jun,440814.52
547,KRW,2010-05-22,0.000838,152,NaN,250000.0,1st,1,Korean Air OSL #1 2010 (Ro36),2224,209.538175,kr,TY,Tae Yang,Jun,440814.52
548,KRW,2009-08-16,0.000807,152,NaN,2000000.0,9th-16th,1,Averatec-Intel Classic #3,2224,1613.423800,kr,TY,Tae Yang,Jun,440814.52
549,KRW,2008-07-13,0.001078,152,NaN,0.0,7th,14,Shinhan Bank Proleague 2008 (Regular Season),2224,0.000000,kr,TY,Tae Yang,Jun,440814.52
614,KRW,2010-08-28,0.000836,152,NaN,500000.0,17th-32nd,1,Bigfile MSL 2010,1002,417.780750,kr,Mvp,Jong Hyun,Jung,404265.42
615,KRW,2010-05-29,0.000837,152,NaN,3000000.0,5th-8th,1,Hana Daetoo MSL 2010,1002,2511.300900,kr,Mvp,Jong Hyun,Jung,404265.42
616,KRW,2010-05-22,0.000838,152,NaN,100000.0,3rd,1,Korean Air OSL #1 2010 (Ro36),1002,83.815270,kr,Mvp,Jong Hyun,Jung,404265.42
617,KRW,2009-08-16,0.000807,152,NaN,2000000.0,9th-16th,1,Averatec-Intel Classic #3,1002,1613.423800,kr,Mvp,Jong Hyun,Jung,404265.42
1446,KRW,2008-07-13,0.001078,152,NaN,0.0,5th,15,Shinhan Bank Proleague 2008 (Regular Season),1001,0.000000,kr,NesTea,Jae Duk,Lim,287702.13
2059,EUR,2008-06-14,1.536653,152,NaN,900.0,5th-6th,1,PGL Season 3 (StarCraft: Brood War),1030,1382.987714,kr,Bomber,Ji Sung,Choi,256952.14
2228,KRW,2011-02-19,0.000901,152,NaN,500000.0,17th-32nd,1,PDPop MSL 2010,2236,450.450450,kr,Stats,Dae Yeob,Kim,244974.71
2229,KRW,2011-01-29,0.000897,152,NaN,100000.0,3rd,1,Bacchus OSL 2010 (Ro36),2236,89.670010,kr,Stats,Dae Yeob,Kim,244974.71
2230,KRW,2010-09-11,0.000858,152,NaN,100000.0,3rd,1,Korean Air OSL #2 2010 (Ro36),2236,85.836910,kr,Stats,Dae Yeob,Kim,244974.71
2231,KRW,2010-08-28,0.000836,152,NaN,2000000.0,9th-16th,1,Bigfile MSL 2010,2236,1671.123000,kr,Stats,Dae Yeob,Kim,244974.71
2232,KRW,2010-05-29,0.000837,152,NaN,500000.0,17th-32nd,1,Hana Daetoo MSL 2010,2236,418.550150,kr,Stats,Dae Yeob,Kim,244974.71
2233,KRW,2010-01-23,0.000868,152,NaN,3000000.0,5th-8th,1,NATE MSL 2009,2236,2603.262600,kr,Stats,Dae Yeob,Kim,244974.71
2234,KRW,2008-07-13,0.001078,152,NaN,0.0,5th,15,Shinhan Bank Proleague 2008 (Regular Season),2236,0.000000,kr,Stats,Dae Yeob,Kim,244974.71
2235,KRW,2017-06-10,0.000889,152,NaN,1600000.0,5th-6th,1,SSL Classic Season 1,3041,1422.400000,kr,Rain,Yoon Jong,Jung,239358.36
2236,KRW,2017-06-03,0.000894,152,NaN,150000.0,17th-32nd,1,Afreeca Starleague Season 3,3041,134.100000,kr,Rain,Yoon Jong,Jung,239358.36
2237,KRW,2017-06-02,0.000891,152,NaN,3000000.0,1st,11,AfreecaTV Clan League,3041,2673.000000,kr,Rain,Yoon Jong,Jung,239358.36
2238,KRW,2017-03-19,0.000885,152,NaN,3000000.0,2nd,3,ASL Team Battle Season 1,3041,2655.000000,kr,Rain,Yoon Jong,Jung,239358.36
2239,KRW,2017-01-22,0.000851,152,NaN,300000.0,9th-16th,1,Afreeca Starleague Season 2,3041,255.300000,kr,Rain,Yoon Jong,Jung,239358.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22572,USD,2016-07-16,1.000000,371,NaN,15000.0,3rd-4th,5,DreamHack All-Stars - Valencia 2016 (HotS),14122,15000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22573,USD,2016-06-20,1.000000,371,NaN,50000.0,3rd-4th,5,DreamHack All-Stars - Summer 2016 (HotS),14122,50000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22574,USD,2016-05-14,1.000000,371,NaN,25000.0,1st,5,DreamHack All-Stars Tours 2016 (HotS),14122,25000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22575,USD,2016-04-24,1.000000,371,NaN,20000.0,2nd,5,ESL Heroes of the Storm Championship - Leicester,14122,20000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22576,USD,2016-04-03,1.000000,371,NaN,25000.0,7th-8th,5,Heroes Spring Global Championship 2016,14122,25000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22577,USD,2016-03-06,1.000000,371,NaN,20000.0,2nd,5,ESL Heroes of the Storm Championship - Katowice,14122,20000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22578,USD,2015-11-07,1.000000,371,NaN,50000.0,3rd-4th,5,BlizzCon 2015 (Heroes),14122,50000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22579,USD,2015-10-04,1.000000,371,NaN,40000.0,1st,5,European Championship 2015 (HotS),14122,40000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22580,USD,2015-08-23,1.000000,371,NaN,1500.0,3rd-4th,5,HWC 2015 - Europe Open Qualifier (August),14122,1500.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22581,EUR,2015-08-09,1.096900,371,NaN,3000.0,3rd,5,WCA 2015 European Qualifiers (HotS),14122,3290.700000,bg,Splendour,Lyubomir,Kozlovski,20.00
22582,USD,2015-08-02,1.000000,371,NaN,5000.0,1st,5,HWC 2015 - Europe Open Qualifier (July),14122,5000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22583,USD,2015-07-16,1.000000,371,NaN,4500.0,2nd,5,DreamHack Open: Valencia 2015 (HotS),14122,4500.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22584,USD,2015-07-13,1.000000,371,NaN,1000.0,1st,5,StormGrounds Invitational,14122,1000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22585,USD,2015-06-15,1.000000,371,NaN,1000.0,3rd,5,DreamHack Summer 2015 (HotS),14122,1000.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22586,EUR,2015-05-30,1.116013,371,NaN,200.0,2nd,5,ZOTAC Cup HotS Monthly Finals May (EU),14122,223.202600,bg,Splendour,Lyubomir,Kozlovski,20.00
22587,USD,2015-05-24,1.000000,371,NaN,100.0,WIN,5,Go4Heroes EU #25,14122,100.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22588,EUR,2015-05-16,1.121970,371,NaN,250.0,WIN,5,ZOTAC Cup Heroes of the Storm #9 (EU),14122,280.492575,bg,Splendour,Lyubomir,Kozlovski,20.00
22589,EUR,2015-05-08,1.121940,371,NaN,2500.0,1st,5,DreamHack Tours 2015 (HotS),14122,2804.850000,bg,Splendour,Lyubomir,Kozlovski,20.00
22590,EUR,2015-04-29,1.081745,371,NaN,200.0,2nd,5,ZOTAC Cup HotS Monthly Finals April (EU),14122,216.349000,bg,Splendour,Lyubomir,Kozlovski,20.00
22591,USD,2015-04-15,1.000000,371,NaN,500.0,1st,5,Dingit.tv Invitational #2,14122,500.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22592,USD,2015-04-12,1.000000,371,NaN,250.0,3rd,5,Enter The Storm - Cup #1,14122,250.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22593,USD,2015-04-05,1.000000,371,NaN,100.0,WIN,5,Go4Heroes EU #18,14122,100.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22594,USD,2015-03-29,1.000000,371,NaN,100.0,WIN,5,Go4Heroes EU #17,14122,100.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22595,EUR,2015-03-28,1.081298,371,NaN,600.0,WIN,5,ZOTAC Cup HotS Monthly Finals March (EU),14122,648.778800,bg,Splendour,Lyubomir,Kozlovski,20.00
22596,EUR,2015-03-26,1.084210,371,NaN,200.0,1st,5,TaKeTV's Heroes Battle Qualifier Main Event,14122,216.842000,bg,Splendour,Lyubomir,Kozlovski,20.00
22597,USD,2015-03-22,1.000000,371,NaN,100.0,WIN,5,Go4Heroes EU #16,14122,100.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22598,USD,2015-03-08,1.000000,371,NaN,100.0,WIN,5,Go4Heroes EU #14,14122,100.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22599,EUR,2015-03-07,1.081298,371,NaN,250.0,WIN,5,ZOTAC Cup Heroes of the Storm #1 (EU),14122,270.324500,bg,Splendour,Lyubomir,Kozlovski,20.00
22600,USD,2015-03-01,1.000000,371,NaN,100.0,WIN,5,Go4Heroes EU #13,14122,100.000000,bg,Splendour,Lyubomir,Kozlovski,20.00
22601,EUR,2015-02-21,1.134480,371,NaN,200.0,WIN,5,TaKeTV's Heroes Battle Qualifier #1,14122,226.896000,bg,Splendour,Lyubomir,Kozlovski,20.00

In [105]:
age = pd.read_csv('dob.csv',header=None)

In [106]:
age.columns = ['drop','PlayerId','DOB']

In [107]:
age = age.drop_duplicates()

In [108]:
age.pop('drop')

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
556    0
557    0
558    0
559    0
560    0
561    0
562    0
563    0
564    0
565    0
566    0
567    0
568    0
569    0
570    0
571    0
572    0
573    0
574    0
575    0
576    0
577    0
578    0
579    0
580    0
581    0
582    0
583    0
584    0
585    0
Name: drop, Length: 576, dtype: int64

In [122]:
age

     PlayerId                 DOB
0        1000       June 17, 1991
1        2272    October 16, 1993
2        1429    January 11, 1997
3        1003        July 2, 1988
4        2268       July 25, 1993
5        2224  September 18, 1994
6        1002   February 12, 1991
7        1007    October 29, 1988
8        1017         May 8, 1993
9        1132     August 24, 1994
10       1257       July 28, 1990
11       4674       July 11, 1992
12       1126       July 28, 1997
13       1227      August 9, 1992
14       1001   December 12, 1982
15       1061     January 1, 1995
16       1158      March 12, 1993
17       3620     October 6, 1995
18       1025       April 1, 1995
19       1086        June 6, 1990
20       1057        June 3, 1991
21       1030    January 16, 1988
22       3818   February 17, 1998
23       2236        May 15, 1992
24       3041     August 14, 1992
25       1426    January 15, 1988
26       2271   November 27, 1991
27       1507     January 9, 1990
28       3657         May 9, 1996
29       3042     August 18, 1992
..        ...                 ...
556     39748     January 7, 1994
557     39750       March 7, 1989
558     39751  September 20, 1984
559     39752        June 3, 1985
560     39753  September 13, 1990
561      1479   September 4, 1984
562      3810   December 15, 1987
563      3865     August 13, 1990
564      1433        May 18, 1989
565      6380    October 27, 1990
566     14127  September 13, 1991
567      4343    January 17, 1991
568     23718       June 20, 1993
569      2304   December 13, 1988
570     11135        May 29, 1992
571      4347      March 26, 1989
572      4387  September 19, 1995
573      6381  September 26, 1987
574      2306       July 30, 1988
575      2312        May 11, 1993
576      2316      March 18, 1988
577      2317       July 30, 1991
578      2318  September 29, 1988
579      2332    December 5, 1989
580      2794     August 27, 1990
581      7139       June 28, 1987
582      4331    February 8, 1989
583     14124   November 30, 1985
584     14129       June 18, 1988
585      7323     August 16, 1990

[576 rows x 2 columns]

In [129]:
df_mrg = df_sc2.merge(age, on='PlayerId',how='outer')

In [130]:
df_mrg

,CurrencyCode,EndDate,ExchangeRate,GameId,Note,Prize,RankText,TeamPlayers,TournamentName,PlayerId,Prize_USD,CountryCode,CurrentHandle,NameFirst,NameLast,TotalUSDPrize,DOB
0,KRW,2016-09-10,0.000905,151,NaN,3000000.0,17th-24th,1,GSL Season 2 2016 (Code S),1000,2714.195100,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
1,USD,2016-02-02,1.000000,151,NaN,1000.0,5th-8th,1,IEM X - Taipei (SC2),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
2,USD,2015-12-20,1.000000,151,NaN,875.0,5th-8th,1,HomeStory Cup XII,1000,875.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
3,USD,2015-12-12,1.000000,151,NaN,600.0,2nd,1,WW3,1000,600.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
4,USD,2015-12-01,1.000000,151,NaN,100.0,WIN,1,Showmatch MC vs. TLO,1000,100.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
5,USD,2015-09-19,1.000000,151,NaN,15000.0,1st,2,Red Bull Battle Grounds - Washington 2015 (Arc...,1000,15000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
6,USD,2015-08-30,1.000000,151,NaN,2490.0,2nd,2,Red Bull Battle Grounds - Santa Monica 2015 (A...,1000,2490.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
7,KRW,2015-04-17,0.000914,151,NaN,400000.0,25th-48th,1,GSL Season 2 2015 (Code A),1000,365.600000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
8,KRW,2015-03-22,0.000898,151,NaN,1500000.0,13th-16th,1,2015 Global StarCraft II League Season 1,1000,1346.825550,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
9,USD,2014-11-08,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2014 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
10,USD,2014-10-05,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 3 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
11,USD,2014-10-03,1.000000,151,NaN,800.0,4th,1,Connecting Professional E-sports #1,1000,800.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
12,USD,2014-09-30,1.000000,151,NaN,3500.0,WIN,3,NationWars II - Korea vs. Norway,1000,3500.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
13,USD,2014-08-31,1.000000,151,NaN,400.0,9th-12th,1,IEM IX - Toronto (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
14,USD,2014-08-03,1.000000,151,NaN,3000.0,3rd-4th,1,Gfinity G3 (Starcraft II),1000,3000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
15,USD,2014-07-20,1.000000,151,NaN,5000.0,2nd,1,DreamHack Valencia 2014 (SC2),1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
16,USD,2014-07-06,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 2 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
17,EUR,2014-06-22,1.359912,151,NaN,50.0,2nd,1,Go4SC2 EU #381,1000,67.995600,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
18,USD,2014-06-16,1.000000,151,NaN,1000.0,7th-8th,1,DreamHack Summer 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
19,USD,2014-06-08,1.000000,151,NaN,6500.0,2nd,1,HomeStory Cup IX,1000,6500.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
20,USD,2014-04-27,1.000000,151,NaN,1000.0,5th-8th,1,DreamHack Bucharest 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
21,EUR,2014-04-20,1.380905,151,NaN,100.0,1st,1,Go4SC2 EU #363,1000,138.090500,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
22,USD,2014-04-13,1.000000,151,NaN,25000.0,1st,1,WCS Europe 2014 Season 1 Premier,1000,25000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
23,USD,2014-02-16,1.000000,151,NaN,400.0,9th-12th,1,IEM VIII - Cologne (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
24,USD,2014-02-07,1.000000,151,NaN,3000.0,1st,1,Warer.com Invitational,1000,3000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
25,USD,2014-02-01,1.000000,151,NaN,4000.0,2nd,1,IEM VIII - Sao Paulo (StarCraft II),1000,4000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
26,SEK,2013-12-09,0.153017,151,NaN,8000.0,4th,1,Fragbite Masters 2013 (StarCraft II),1000,1224.139528,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
27,USD,2013-11-24,1.000000,151,NaN,4000.0,4th,1,Red Bull Battle Grounds: Grand Finals New York...,1000,4000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
28,USD,2013-11-09,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2013 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
29,USD,2013-10-27,1.000000,151,NaN,7500.0,5th-8th,1,WCS 2013 Season 3 Finals,1000,7500.000000,kr,MC,Min Chul,Jang,506645.42,"June 17, 1991"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19939,EUR,2013-01-22,1.282848,151,NaN,500.0,WIN,1,Go4SC2 November 2012 Monthly Finals,1257,641.424000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19940,USD,2013-01-20,1.000000,151,NaN,650.0,17th-20th,1,IEM VII - Katowice (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19941,USD,2012-12-22,1.000000,151,NaN,10000.0,1st,1,HomeStory Cup VI,1257,10000.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19942,EUR,2012-12-16,1.311272,151,NaN,200.0,WIN,1,Go4SC2 EU #252,1257,262.254400,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19943,USD,2012-12-16,1.000000,151,NaN,1000.0,3rd,1,PokerStrategy.com League,1257,1000.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19944,SEK,2012-12-09,0.149689,151,NaN,30000.0,2nd,1,THOR Open 2012 (Starcraft II),1257,4490.681835,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19945,USD,2012-12-02,1.000000,151,NaN,500.0,13th-16th,1,IGN Pro League Season 5 (Starcraft II),1257,500.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19946,EUR,2012-11-27,1.271412,151,NaN,450.0,1st,1,GameCreds Invitational,1257,572.135417,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19947,SEK,2012-11-24,0.150917,151,NaN,25000.0,5th-8th,1,DreamHack Winter 2012 (StarCraft II),1257,3772.929982,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19948,EUR,2012-11-16,1.271412,151,NaN,1000.0,2nd,1,Acer StarCraft Challenge,1257,1271.412038,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19949,EUR,2012-11-04,1.282848,151,NaN,200.0,WIN,1,Go4SC2 EU #241,1257,256.569600,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19950,USD,2012-09-28,1.000000,151,NaN,300.0,WIN,1,BO69 FXOBabyKnight vs GLSnute Showmatch,1257,300.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19951,EUR,2012-09-13,1.299350,151,NaN,200.0,3rd,1,GIGABYTE NVIDIA Invitational #4,1257,259.870000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19952,USD,2012-09-02,1.000000,151,NaN,800.0,3rd,1,Battle at Ministry of Win: get outPlayed,1257,800.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19953,USD,2012-08-25,1.000000,151,NaN,3000.0,2nd,1,Campus Party: Europe in Berlin (Starcraft II),1257,3000.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19954,USD,2012-07-28,1.000000,151,NaN,350.0,4th,1,WCS 2012: Norway,1257,350.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19955,EUR,2012-07-18,1.226227,151,NaN,75.0,2nd,1,Antec Attack #25,1257,91.967023,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19956,EUR,2012-07-16,1.226548,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #65,1257,122.654847,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19957,EUR,2012-04-16,1.306836,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #54,1257,130.683619,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19958,USD,2012-04-01,1.000000,151,NaN,2000.0,1st,1,ONOG i2 Starcraft 2 Invitational,1257,2000.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19959,EUR,2012-03-29,1.320784,151,NaN,250.0,1st,1,4PL Close Combat Cup 2012 March Finals,1257,330.196000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19960,EUR,2012-03-08,1.320784,151,NaN,50.0,WIN,1,4PL Close Combat Cup 2012 March Qualifier #3,1257,66.039200,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19961,NOK,2012-02-24,0.179566,151,NaN,20000.0,1st,1,Nemean LAN 2012,1257,3591.314674,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19962,USD,2012-02-11,1.000000,151,NaN,650.0,9th-12th,1,IEM VI - Sao Paulo (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19963,EUR,2011-11-28,1.333371,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #41,1257,133.337075,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19964,NOK,2011-10-08,0.171574,151,NaN,20000.0,1st,1,Polar Party 20 (StarCraft II),1257,3431.473474,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19965,EUR,2011-06-13,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #50,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19966,EUR,2011-06-09,1.439143,151,NaN,50.0,2nd,1,4PL Close Combat Cup 2011 #49,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19967,EUR,2011-06-06,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #48,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"
19968,EUR,2011-05-16,1.431440,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #42,1257,71.572000,no,Snute,Jens,Aasgaard,334526.98,"July 28, 1990"

In [131]:
df_mrg['EndDate'] = pd.to_datetime(df_mrg.EndDate)

In [132]:
df_mrg['DOB']=pd.to_datetime(df_mrg.DOB)

In [192]:
df_mrg['Age_at_win']=(df_mrg['EndDate']-df_mrg['DOB']).astype('timedelta64[Y]')

In [201]:
df_mrg

,CurrencyCode,EndDate,ExchangeRate,GameId,Note,Prize,RankText,TeamPlayers,TournamentName,PlayerId,Prize_USD,CountryCode,CurrentHandle,NameFirst,NameLast,TotalUSDPrize,DOB,Age_at_win
0,KRW,2016-09-10,0.000905,151,NaN,3000000.0,17th-24th,1,GSL Season 2 2016 (Code S),1000,2714.195100,kr,MC,Min Chul,Jang,506645.42,1991-06-17,25.0
1,USD,2016-02-02,1.000000,151,NaN,1000.0,5th-8th,1,IEM X - Taipei (SC2),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,24.0
2,USD,2015-12-20,1.000000,151,NaN,875.0,5th-8th,1,HomeStory Cup XII,1000,875.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,24.0
3,USD,2015-12-12,1.000000,151,NaN,600.0,2nd,1,WW3,1000,600.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,24.0
4,USD,2015-12-01,1.000000,151,NaN,100.0,WIN,1,Showmatch MC vs. TLO,1000,100.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,24.0
5,USD,2015-09-19,1.000000,151,NaN,15000.0,1st,2,Red Bull Battle Grounds - Washington 2015 (Arc...,1000,15000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,24.0
6,USD,2015-08-30,1.000000,151,NaN,2490.0,2nd,2,Red Bull Battle Grounds - Santa Monica 2015 (A...,1000,2490.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,24.0
7,KRW,2015-04-17,0.000914,151,NaN,400000.0,25th-48th,1,GSL Season 2 2015 (Code A),1000,365.600000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
8,KRW,2015-03-22,0.000898,151,NaN,1500000.0,13th-16th,1,2015 Global StarCraft II League Season 1,1000,1346.825550,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
9,USD,2014-11-08,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2014 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
10,USD,2014-10-05,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 3 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
11,USD,2014-10-03,1.000000,151,NaN,800.0,4th,1,Connecting Professional E-sports #1,1000,800.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
12,USD,2014-09-30,1.000000,151,NaN,3500.0,WIN,3,NationWars II - Korea vs. Norway,1000,3500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
13,USD,2014-08-31,1.000000,151,NaN,400.0,9th-12th,1,IEM IX - Toronto (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
14,USD,2014-08-03,1.000000,151,NaN,3000.0,3rd-4th,1,Gfinity G3 (Starcraft II),1000,3000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
15,USD,2014-07-20,1.000000,151,NaN,5000.0,2nd,1,DreamHack Valencia 2014 (SC2),1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
16,USD,2014-07-06,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 2 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
17,EUR,2014-06-22,1.359912,151,NaN,50.0,2nd,1,Go4SC2 EU #381,1000,67.995600,kr,MC,Min Chul,Jang,506645.42,1991-06-17,23.0
18,USD,2014-06-16,1.000000,151,NaN,1000.0,7th-8th,1,DreamHack Summer 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
19,USD,2014-06-08,1.000000,151,NaN,6500.0,2nd,1,HomeStory Cup IX,1000,6500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
20,USD,2014-04-27,1.000000,151,NaN,1000.0,5th-8th,1,DreamHack Bucharest 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
21,EUR,2014-04-20,1.380905,151,NaN,100.0,1st,1,Go4SC2 EU #363,1000,138.090500,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
22,USD,2014-04-13,1.000000,151,NaN,25000.0,1st,1,WCS Europe 2014 Season 1 Premier,1000,25000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
23,USD,2014-02-16,1.000000,151,NaN,400.0,9th-12th,1,IEM VIII - Cologne (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
24,USD,2014-02-07,1.000000,151,NaN,3000.0,1st,1,Warer.com Invitational,1000,3000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
25,USD,2014-02-01,1.000000,151,NaN,4000.0,2nd,1,IEM VIII - Sao Paulo (StarCraft II),1000,4000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
26,SEK,2013-12-09,0.153017,151,NaN,8000.0,4th,1,Fragbite Masters 2013 (StarCraft II),1000,1224.139528,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
27,USD,2013-11-24,1.000000,151,NaN,4000.0,4th,1,Red Bull Battle Grounds: Grand Finals New York...,1000,4000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
28,USD,2013-11-09,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2013 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
29,USD,2013-10-27,1.000000,151,NaN,7500.0,5th-8th,1,WCS 2013 Season 3 Finals,1000,7500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19939,EUR,2013-01-22,1.282848,151,NaN,500.0,WIN,1,Go4SC2 November 2012 Monthly Finals,1257,641.424000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19940,USD,2013-01-20,1.000000,151,NaN,650.0,17th-20th,1,IEM VII - Katowice (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19941,USD,2012-12-22,1.000000,151,NaN,10000.0,1st,1,HomeStory Cup VI,1257,10000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19942,EUR,2012-12-16,1.311272,151,NaN,200.0,WIN,1,Go4SC2 EU #252,1257,262.254400,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19943,USD,2012-12-16,1.000000,151,NaN,1000.0,3rd,1,PokerStrategy.com League,1257,1000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19944,SEK,2012-12-09,0.149689,151,NaN,30000.0,2nd,1,THOR Open 2012 (Starcraft II),1257,4490.681835,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19945,USD,2012-12-02,1.000000,151,NaN,500.0,13th-16th,1,IGN Pro League Season 5 (Starcraft II),1257,500.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19946,EUR,2012-11-27,1.271412,151,NaN,450.0,1st,1,GameCreds Invitational,1257,572.135417,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19947,SEK,2012-11-24,0.150917,151,NaN,25000.0,5th-8th,1,DreamHack Winter 2012 (StarCraft II),1257,3772.929982,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19948,EUR,2012-11-16,1.271412,151,NaN,1000.0,2nd,1,Acer StarCraft Challenge,1257,1271.412038,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19949,EUR,2012-11-04,1.282848,151,NaN,200.0,WIN,1,Go4SC2 EU #241,1257,256.569600,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19950,USD,2012-09-28,1.000000,151,NaN,300.0,WIN,1,BO69 FXOBabyKnight vs GLSnute Showmatch,1257,300.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19951,EUR,2012-09-13,1.299350,151,NaN,200.0,3rd,1,GIGABYTE NVIDIA Invitational #4,1257,259.870000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19952,USD,2012-09-02,1.000000,151,NaN,800.0,3rd,1,Battle at Ministry of Win: get outPlayed,1257,800.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19953,USD,2012-08-25,1.000000,151,NaN,3000.0,2nd,1,Campus Party: Europe in Berlin (Starcraft II),1257,3000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19954,USD,2012-07-28,1.000000,151,NaN,350.0,4th,1,WCS 2012: Norway,1257,350.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,22.0
19955,EUR,2012-07-18,1.226227,151,NaN,75.0,2nd,1,Antec Attack #25,1257,91.967023,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19956,EUR,2012-07-16,1.226548,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #65,1257,122.654847,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19957,EUR,2012-04-16,1.306836,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #54,1257,130.683619,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19958,USD,2012-04-01,1.000000,151,NaN,2000.0,1st,1,ONOG i2 Starcraft 2 Invitational,1257,2000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19959,EUR,2012-03-29,1.320784,151,NaN,250.0,1st,1,4PL Close Combat Cup 2012 March Finals,1257,330.196000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19960,EUR,2012-03-08,1.320784,151,NaN,50.0,WIN,1,4PL Close Combat Cup 2012 March Qualifier #3,1257,66.039200,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19961,NOK,2012-02-24,0.179566,151,NaN,20000.0,1st,1,Nemean LAN 2012,1257,3591.314674,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19962,USD,2012-02-11,1.000000,151,NaN,650.0,9th-12th,1,IEM VI - Sao Paulo (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19963,EUR,2011-11-28,1.333371,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #41,1257,133.337075,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19964,NOK,2011-10-08,0.171574,151,NaN,20000.0,1st,1,Polar Party 20 (StarCraft II),1257,3431.473474,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,21.0
19965,EUR,2011-06-13,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #50,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,20.0
19966,EUR,2011-06-09,1.439143,151,NaN,50.0,2nd,1,4PL Close Combat Cup 2011 #49,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,20.0
19967,EUR,2011-06-06,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #48,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,20.0
19968,EUR,2011-05-16,1.431440,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #42,1257,71.572000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,20.0

In [148]:
df_mrg['Age_at_win'].argmax()

17275

In [160]:
df_mrg['Age_at_win'].min()

Timedelta('4814 days 00:00:00')

In [163]:
df_mrg['Age_at_win'].argmin()

19703

In [164]:
df_mrg.iloc[19703]

CurrencyCode                                   KRW
EndDate                        2010-10-02 00:00:00
ExchangeRate                           0.000884878
GameId                                         151
Note                                           NaN
Prize                                       500000
RankText                                 17th-32nd
TeamPlayers                                      1
TournamentName                   GSL Open Season 1
PlayerId                                      1126
Prize_USD                                  442.439
CountryCode                                     kr
CurrentHandle                                 Maru
NameFirst                                Sung Choo
NameLast                                       Cho
TotalUSDPrize                               318354
DOB                            1997-07-28 00:00:00
Age               <property object at 0x10f79e368>
Age_at_win                      4814 days 00:00:00
Name: 19703, dtype: object

In [186]:
df_mrg

,CurrencyCode,EndDate,ExchangeRate,GameId,Note,Prize,RankText,TeamPlayers,TournamentName,PlayerId,Prize_USD,CountryCode,CurrentHandle,NameFirst,NameLast,TotalUSDPrize,DOB,Age_at_win,WinDays
0,KRW,2016-09-10,0.000905,151,NaN,3000000.0,17th-24th,1,GSL Season 2 2016 (Code S),1000,2714.195100,kr,MC,Min Chul,Jang,506645.42,1991-06-17,9217 days,2181777534246575
1,USD,2016-02-02,1.000000,151,NaN,1000.0,5th-8th,1,IEM X - Taipei (SC2),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8996 days,2129464109589041
2,USD,2015-12-20,1.000000,151,NaN,875.0,5th-8th,1,HomeStory Cup XII,1000,875.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8952 days,2119048767123287
3,USD,2015-12-12,1.000000,151,NaN,600.0,2nd,1,WW3,1000,600.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8944 days,2117155068493150
4,USD,2015-12-01,1.000000,151,NaN,100.0,WIN,1,Showmatch MC vs. TLO,1000,100.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8933 days,2114551232876712
5,USD,2015-09-19,1.000000,151,NaN,15000.0,1st,2,Red Bull Battle Grounds - Washington 2015 (Arc...,1000,15000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8860 days,2097271232876712
6,USD,2015-08-30,1.000000,151,NaN,2490.0,2nd,2,Red Bull Battle Grounds - Santa Monica 2015 (A...,1000,2490.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8840 days,2092536986301369
7,KRW,2015-04-17,0.000914,151,NaN,400000.0,25th-48th,1,GSL Season 2 2015 (Code A),1000,365.600000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8705 days,2060580821917808
8,KRW,2015-03-22,0.000898,151,NaN,1500000.0,13th-16th,1,2015 Global StarCraft II League Season 1,1000,1346.825550,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8679 days,2054426301369863
9,USD,2014-11-08,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2014 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8545 days,2022706849315068
10,USD,2014-10-05,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 3 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8511 days,2014658630136986
11,USD,2014-10-03,1.000000,151,NaN,800.0,4th,1,Connecting Professional E-sports #1,1000,800.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8509 days,2014185205479452
12,USD,2014-09-30,1.000000,151,NaN,3500.0,WIN,3,NationWars II - Korea vs. Norway,1000,3500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8506 days,2013475068493150
13,USD,2014-08-31,1.000000,151,NaN,400.0,9th-12th,1,IEM IX - Toronto (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8476 days,2006373698630137
14,USD,2014-08-03,1.000000,151,NaN,3000.0,3rd-4th,1,Gfinity G3 (Starcraft II),1000,3000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8448 days,1999745753424657
15,USD,2014-07-20,1.000000,151,NaN,5000.0,2nd,1,DreamHack Valencia 2014 (SC2),1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8434 days,1996431780821917
16,USD,2014-07-06,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 2 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8420 days,1993117808219178
17,EUR,2014-06-22,1.359912,151,NaN,50.0,2nd,1,Go4SC2 EU #381,1000,67.995600,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8406 days,1989803835616438
18,USD,2014-06-16,1.000000,151,NaN,1000.0,7th-8th,1,DreamHack Summer 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8400 days,1988383561643835
19,USD,2014-06-08,1.000000,151,NaN,6500.0,2nd,1,HomeStory Cup IX,1000,6500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8392 days,1986489863013698
20,USD,2014-04-27,1.000000,151,NaN,1000.0,5th-8th,1,DreamHack Bucharest 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8350 days,1976547945205479
21,EUR,2014-04-20,1.380905,151,NaN,100.0,1st,1,Go4SC2 EU #363,1000,138.090500,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8343 days,1974890958904109
22,USD,2014-04-13,1.000000,151,NaN,25000.0,1st,1,WCS Europe 2014 Season 1 Premier,1000,25000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8336 days,1973233972602739
23,USD,2014-02-16,1.000000,151,NaN,400.0,9th-12th,1,IEM VIII - Cologne (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8280 days,1959978082191780
24,USD,2014-02-07,1.000000,151,NaN,3000.0,1st,1,Warer.com Invitational,1000,3000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8271 days,1957847671232876
25,USD,2014-02-01,1.000000,151,NaN,4000.0,2nd,1,IEM VIII - Sao Paulo (StarCraft II),1000,4000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8265 days,1956427397260274
26,SEK,2013-12-09,0.153017,151,NaN,8000.0,4th,1,Fragbite Masters 2013 (StarCraft II),1000,1224.139528,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8211 days,1943644931506849
27,USD,2013-11-24,1.000000,151,NaN,4000.0,4th,1,Red Bull Battle Grounds: Grand Finals New York...,1000,4000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8196 days,1940094246575342
28,USD,2013-11-09,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2013 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8181 days,1936543561643835
29,USD,2013-10-27,1.000000,151,NaN,7500.0,5th-8th,1,WCS 2013 Season 3 Finals,1000,7500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8168 days,1933466301369863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19939,EUR,2013-01-22,1.282848,151,NaN,500.0,WIN,1,Go4SC2 November 2012 Monthly Finals,1257,641.424000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8214 days,1944355068493150
19940,USD,2013-01-20,1.000000,151,NaN,650.0,17th-20th,1,IEM VII - Katowice (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8212 days,1943881643835616
19941,USD,2012-12-22,1.000000,151,NaN,10000.0,1st,1,HomeStory Cup VI,1257,10000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8183 days,1937016986301369
19942,EUR,2012-12-16,1.311272,151,NaN,200.0,WIN,1,Go4SC2 EU #252,1257,262.254400,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8177 days,1935596712328767
19943,USD,2012-12-16,1.000000,151,NaN,1000.0,3rd,1,PokerStrategy.com League,1257,1000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8177 days,1935596712328767
19944,SEK,2012-12-09,0.149689,151,NaN,30000.0,2nd,1,THOR Open 2012 (Starcraft II),1257,4490.681835,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8170 days,1933939726027397
19945,USD,2012-12-02,1.000000,151,NaN,500.0,13th-16th,1,IGN Pro League Season 5 (Starcraft II),1257,500.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8163 days,1932282739726027
19946,EUR,2012-11-27,1.271412,151,NaN,450.0,1st,1,GameCreds Invitational,1257,572.135417,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8158 days,1931099178082191
19947,SEK,2012-11-24,0.150917,151,NaN,25000.0,5th-8th,1,DreamHack Winter 2012 (StarCraft II),1257,3772.929982,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8155 days,1930389041095890
19948,EUR,2012-11-16,1.271412,151,NaN,1000.0,2nd,1,Acer StarCraft Challenge,1257,1271.412038,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8147 days,1928495342465753
19949,EUR,2012-11-04,1.282848,151,NaN,200.0,WIN,1,Go4SC2 EU #241,1257,256.569600,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8135 days,1925654794520548
19950,USD,2012-09-28,1.000000,151,NaN,300.0,WIN,1,BO69 FXOBabyKnight vs GLSnute Showmatch,1257,300.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8098 days,1916896438356164
19951,EUR,2012-09-13,1.299350,151,NaN,200.0,3rd,1,GIGABYTE NVIDIA Invitational #4,1257,259.870000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8083 days,1913345753424657
19952,USD,2012-09-02,1.000000,151,NaN,800.0,3rd,1,Battle at Ministry of Win: get outPlayed,1257,800.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8072 days,1910741917808219
19953,USD,2012-08-25,1.000000,151,NaN,3000.0,2nd,1,Campus Party: Europe in Berlin (Starcraft II),1257,3000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8064 days,1908848219178082
19954,USD,2012-07-28,1.000000,151,NaN,350.0,4th,1,WCS 2012: Norway,1257,350.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8036 days,1902220273972602
19955,EUR,2012-07-18,1.226227,151,NaN,75.0,2nd,1,Antec Attack #25,1257,91.967023,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8026 days,1899853150684931
19956,EUR,2012-07-16,1.226548,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #65,1257,122.654847,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8024 days,1899379726027397
19957,EUR,2012-04-16,1.306836,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #54,1257,130.683619,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7933 days,1877838904109589
19958,USD,2012-04-01,1.000000,151,NaN,2000.0,1st,1,ONOG i2 Starcraft 2 Invitational,1257,2000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7918 days,1874288219178082
19959,EUR,2012-03-29,1.320784,151,NaN,250.0,1st,1,4PL Close Combat Cup 2012 March Finals,1257,330.196000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7915 days,1873578082191780
19960,EUR,2012-03-08,1.320784,151,NaN,50.0,WIN,1,4PL Close Combat Cup 2012 March Qualifier #3,1257,66.039200,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7894 days,1868607123287671
19961,NOK,2012-02-24,0.179566,151,NaN,20000.0,1st,1,Nemean LAN 2012,1257,3591.314674,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7881 days,1865529863013698
19962,USD,2012-02-11,1.000000,151,NaN,650.0,9th-12th,1,IEM VI - Sao Paulo (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7868 days,1862452602739726
19963,EUR,2011-11-28,1.333371,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #41,1257,133.337075,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7793 days,1844699178082191
19964,NOK,2011-10-08,0.171574,151,NaN,20000.0,1st,1,Polar Party 20 (StarCraft II),1257,3431.473474,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7742 days,1832626849315068
19965,EUR,2011-06-13,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #50,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7625 days,1804931506849315
19966,EUR,2011-06-09,1.439143,151,NaN,50.0,2nd,1,4PL Close Combat Cup 2011 #49,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7621 days,1803984657534246
19967,EUR,2011-06-06,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #48,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7618 days,1803274520547945
19968,EUR,2011-05-16,1.431440,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #42,1257,71.572000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7597 days,1798303561643835

In [206]:
source = ColumnDataSource(df_mrg)
p = Histogram(df_mrg['Age_at_win'].dropna())
show(p)

AttributeError: 'numpy.float64' object has no attribute 'type'

In [188]:
df_mrg['Age_at_win']=(df_mrg['Age_at_win'])

In [189]:
df_mrg

,CurrencyCode,EndDate,ExchangeRate,GameId,Note,Prize,RankText,TeamPlayers,TournamentName,PlayerId,Prize_USD,CountryCode,CurrentHandle,NameFirst,NameLast,TotalUSDPrize,DOB,Age_at_win,WinDays
0,KRW,2016-09-10,0.000905,151,NaN,3000000.0,17th-24th,1,GSL Season 2 2016 (Code S),1000,2714.195100,kr,MC,Min Chul,Jang,506645.42,1991-06-17,9217 days,796348800000000000
1,USD,2016-02-02,1.000000,151,NaN,1000.0,5th-8th,1,IEM X - Taipei (SC2),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8996 days,777254400000000000
2,USD,2015-12-20,1.000000,151,NaN,875.0,5th-8th,1,HomeStory Cup XII,1000,875.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8952 days,773452800000000000
3,USD,2015-12-12,1.000000,151,NaN,600.0,2nd,1,WW3,1000,600.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8944 days,772761600000000000
4,USD,2015-12-01,1.000000,151,NaN,100.0,WIN,1,Showmatch MC vs. TLO,1000,100.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8933 days,771811200000000000
5,USD,2015-09-19,1.000000,151,NaN,15000.0,1st,2,Red Bull Battle Grounds - Washington 2015 (Arc...,1000,15000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8860 days,765504000000000000
6,USD,2015-08-30,1.000000,151,NaN,2490.0,2nd,2,Red Bull Battle Grounds - Santa Monica 2015 (A...,1000,2490.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8840 days,763776000000000000
7,KRW,2015-04-17,0.000914,151,NaN,400000.0,25th-48th,1,GSL Season 2 2015 (Code A),1000,365.600000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8705 days,752112000000000000
8,KRW,2015-03-22,0.000898,151,NaN,1500000.0,13th-16th,1,2015 Global StarCraft II League Season 1,1000,1346.825550,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8679 days,749865600000000000
9,USD,2014-11-08,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2014 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8545 days,738288000000000000
10,USD,2014-10-05,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 3 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8511 days,735350400000000000
11,USD,2014-10-03,1.000000,151,NaN,800.0,4th,1,Connecting Professional E-sports #1,1000,800.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8509 days,735177600000000000
12,USD,2014-09-30,1.000000,151,NaN,3500.0,WIN,3,NationWars II - Korea vs. Norway,1000,3500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8506 days,734918400000000000
13,USD,2014-08-31,1.000000,151,NaN,400.0,9th-12th,1,IEM IX - Toronto (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8476 days,732326400000000000
14,USD,2014-08-03,1.000000,151,NaN,3000.0,3rd-4th,1,Gfinity G3 (Starcraft II),1000,3000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8448 days,729907200000000000
15,USD,2014-07-20,1.000000,151,NaN,5000.0,2nd,1,DreamHack Valencia 2014 (SC2),1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8434 days,728697600000000000
16,USD,2014-07-06,1.000000,151,NaN,5000.0,5th-8th,1,WCS Europe 2014 Season 2 Premier,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8420 days,727488000000000000
17,EUR,2014-06-22,1.359912,151,NaN,50.0,2nd,1,Go4SC2 EU #381,1000,67.995600,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8406 days,726278400000000000
18,USD,2014-06-16,1.000000,151,NaN,1000.0,7th-8th,1,DreamHack Summer 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8400 days,725760000000000000
19,USD,2014-06-08,1.000000,151,NaN,6500.0,2nd,1,HomeStory Cup IX,1000,6500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8392 days,725068800000000000
20,USD,2014-04-27,1.000000,151,NaN,1000.0,5th-8th,1,DreamHack Bucharest 2014 (StarCraft II),1000,1000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8350 days,721440000000000000
21,EUR,2014-04-20,1.380905,151,NaN,100.0,1st,1,Go4SC2 EU #363,1000,138.090500,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8343 days,720835200000000000
22,USD,2014-04-13,1.000000,151,NaN,25000.0,1st,1,WCS Europe 2014 Season 1 Premier,1000,25000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8336 days,720230400000000000
23,USD,2014-02-16,1.000000,151,NaN,400.0,9th-12th,1,IEM VIII - Cologne (StarCraft II),1000,400.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8280 days,715392000000000000
24,USD,2014-02-07,1.000000,151,NaN,3000.0,1st,1,Warer.com Invitational,1000,3000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8271 days,714614400000000000
25,USD,2014-02-01,1.000000,151,NaN,4000.0,2nd,1,IEM VIII - Sao Paulo (StarCraft II),1000,4000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8265 days,714096000000000000
26,SEK,2013-12-09,0.153017,151,NaN,8000.0,4th,1,Fragbite Masters 2013 (StarCraft II),1000,1224.139528,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8211 days,709430400000000000
27,USD,2013-11-24,1.000000,151,NaN,4000.0,4th,1,Red Bull Battle Grounds: Grand Finals New York...,1000,4000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8196 days,708134400000000000
28,USD,2013-11-09,1.000000,151,NaN,5000.0,9th-16th,1,WCS 2013 Global Finals,1000,5000.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8181 days,706838400000000000
29,USD,2013-10-27,1.000000,151,NaN,7500.0,5th-8th,1,WCS 2013 Season 3 Finals,1000,7500.000000,kr,MC,Min Chul,Jang,506645.42,1991-06-17,8168 days,705715200000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19939,EUR,2013-01-22,1.282848,151,NaN,500.0,WIN,1,Go4SC2 November 2012 Monthly Finals,1257,641.424000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8214 days,709689600000000000
19940,USD,2013-01-20,1.000000,151,NaN,650.0,17th-20th,1,IEM VII - Katowice (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8212 days,709516800000000000
19941,USD,2012-12-22,1.000000,151,NaN,10000.0,1st,1,HomeStory Cup VI,1257,10000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8183 days,707011200000000000
19942,EUR,2012-12-16,1.311272,151,NaN,200.0,WIN,1,Go4SC2 EU #252,1257,262.254400,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8177 days,706492800000000000
19943,USD,2012-12-16,1.000000,151,NaN,1000.0,3rd,1,PokerStrategy.com League,1257,1000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8177 days,706492800000000000
19944,SEK,2012-12-09,0.149689,151,NaN,30000.0,2nd,1,THOR Open 2012 (Starcraft II),1257,4490.681835,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8170 days,705888000000000000
19945,USD,2012-12-02,1.000000,151,NaN,500.0,13th-16th,1,IGN Pro League Season 5 (Starcraft II),1257,500.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8163 days,705283200000000000
19946,EUR,2012-11-27,1.271412,151,NaN,450.0,1st,1,GameCreds Invitational,1257,572.135417,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8158 days,704851200000000000
19947,SEK,2012-11-24,0.150917,151,NaN,25000.0,5th-8th,1,DreamHack Winter 2012 (StarCraft II),1257,3772.929982,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8155 days,704592000000000000
19948,EUR,2012-11-16,1.271412,151,NaN,1000.0,2nd,1,Acer StarCraft Challenge,1257,1271.412038,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8147 days,703900800000000000
19949,EUR,2012-11-04,1.282848,151,NaN,200.0,WIN,1,Go4SC2 EU #241,1257,256.569600,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8135 days,702864000000000000
19950,USD,2012-09-28,1.000000,151,NaN,300.0,WIN,1,BO69 FXOBabyKnight vs GLSnute Showmatch,1257,300.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8098 days,699667200000000000
19951,EUR,2012-09-13,1.299350,151,NaN,200.0,3rd,1,GIGABYTE NVIDIA Invitational #4,1257,259.870000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8083 days,698371200000000000
19952,USD,2012-09-02,1.000000,151,NaN,800.0,3rd,1,Battle at Ministry of Win: get outPlayed,1257,800.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8072 days,697420800000000000
19953,USD,2012-08-25,1.000000,151,NaN,3000.0,2nd,1,Campus Party: Europe in Berlin (Starcraft II),1257,3000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8064 days,696729600000000000
19954,USD,2012-07-28,1.000000,151,NaN,350.0,4th,1,WCS 2012: Norway,1257,350.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8036 days,694310400000000000
19955,EUR,2012-07-18,1.226227,151,NaN,75.0,2nd,1,Antec Attack #25,1257,91.967023,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8026 days,693446400000000000
19956,EUR,2012-07-16,1.226548,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #65,1257,122.654847,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,8024 days,693273600000000000
19957,EUR,2012-04-16,1.306836,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #54,1257,130.683619,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7933 days,685411200000000000
19958,USD,2012-04-01,1.000000,151,NaN,2000.0,1st,1,ONOG i2 Starcraft 2 Invitational,1257,2000.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7918 days,684115200000000000
19959,EUR,2012-03-29,1.320784,151,NaN,250.0,1st,1,4PL Close Combat Cup 2012 March Finals,1257,330.196000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7915 days,683856000000000000
19960,EUR,2012-03-08,1.320784,151,NaN,50.0,WIN,1,4PL Close Combat Cup 2012 March Qualifier #3,1257,66.039200,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7894 days,682041600000000000
19961,NOK,2012-02-24,0.179566,151,NaN,20000.0,1st,1,Nemean LAN 2012,1257,3591.314674,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7881 days,680918400000000000
19962,USD,2012-02-11,1.000000,151,NaN,650.0,9th-12th,1,IEM VI - Sao Paulo (StarCraft II),1257,650.000000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7868 days,679795200000000000
19963,EUR,2011-11-28,1.333371,151,NaN,100.0,WIN,1,GameCreds SC2 Cup #41,1257,133.337075,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7793 days,673315200000000000
19964,NOK,2011-10-08,0.171574,151,NaN,20000.0,1st,1,Polar Party 20 (StarCraft II),1257,3431.473474,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7742 days,668908800000000000
19965,EUR,2011-06-13,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #50,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7625 days,658800000000000000
19966,EUR,2011-06-09,1.439143,151,NaN,50.0,2nd,1,4PL Close Combat Cup 2011 #49,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7621 days,658454400000000000
19967,EUR,2011-06-06,1.439143,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #48,1257,71.957150,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7618 days,658195200000000000
19968,EUR,2011-05-16,1.431440,151,NaN,50.0,WIN,2,4PL Team Action Cup 2011 #42,1257,71.572000,no,Snute,Jens,Aasgaard,334526.98,1990-07-28,7597 days,656380800000000000

In [205]:
df_mrg['RankText'].unique()

array(['17th-24th', '5th-8th', '2nd', 'WIN', '1st', '25th-48th',
       '13th-16th', '9th-16th', '4th', '9th-12th', '3rd-4th', '7th-8th',
       '25th-32nd', 'Round 2', '3rd', '17th-32nd', 'See Note', 'Round 3',
       'Code S', 'LOSE', '6th', '5th-12th', '33rd-64th', '9th',
       '31st-60th', '5th-6th', '5th', 'DISQUALIFIED', '9th-11th',
       '9th-10th', 'Round 1', '4 Wins', '1st-8th', '11th-12th', '1 Win',
       '3 Wins', '7 Wins', '-', '2 Wins', '7th', '7th-10th', '8 Wins',
       '5 Wins', '6th-8th', '8th', '21st-24th', '1st-4th', '15th-18th',
       '19th-26th', '17th-20th', '27th-32nd', '11th-14th', '13th',
       '25th-28th', '10th', '12th', '13th-14th', '10th-12th', '29th-36th',
       '10th-11th', '7th-12th', '37th-44th', '11th', '14th', '15th'], dtype=object)

In [212]:
df_mrg['Win']=df_mrg['RankText']

In [220]:
rank = pd.get_dummies(df_mrg.RankText)

In [221]:
rank.columns

Index(['-', '1 Win', '10th', '10th-11th', '10th-12th', '11th', '11th-12th',
       '11th-14th', '12th', '13th', '13th-14th', '13th-16th', '14th', '15th',
       '15th-18th', '17th-20th', '17th-24th', '17th-32nd', '19th-26th', '1st',
       '1st-4th', '1st-8th', '2 Wins', '21st-24th', '25th-28th', '25th-32nd',
       '25th-48th', '27th-32nd', '29th-36th', '2nd', '3 Wins', '31st-60th',
       '33rd-64th', '37th-44th', '3rd', '3rd-4th', '4 Wins', '4th', '5 Wins',
       '5th', '5th-12th', '5th-6th', '5th-8th', '6th', '6th-8th', '7 Wins',
       '7th', '7th-10th', '7th-12th', '7th-8th', '8 Wins', '8th', '9th',
       '9th-10th', '9th-11th', '9th-12th', '9th-16th', 'Code S',
       'DISQUALIFIED', 'LOSE', 'Round 1', 'Round 2', 'Round 3', 'See Note',
       'WIN'],
      dtype='object')

In [227]:
rank2 = rank['1st']+rank['WIN']

In [229]:
rank2 #note rank2 is column for 1st Place/Winner

0        0
1        0
2        0
3        0
4        1
5        1
6        0
7        0
8        0
9        0
10       0
11       0
12       1
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       1
22       1
23       0
24       1
25       0
26       0
27       0
28       0
29       0
        ..
19939    1
19940    0
19941    1
19942    1
19943    0
19944    0
19945    0
19946    1
19947    0
19948    0
19949    1
19950    1
19951    0
19952    0
19953    0
19954    0
19955    0
19956    1
19957    1
19958    1
19959    1
19960    1
19961    1
19962    0
19963    1
19964    1
19965    1
19966    0
19967    1
19968    1
Length: 19969, dtype: uint8

In [230]:
j = {'PlayerId': 1000, 'history': {'[<a href="/teams/141-cj-entus">CJ Entus</a>]': "['2016-05-23 ⇒ 2016-10-18']", '[<a href="/teams/359-trig-esports">Trig Esports</a>]': "['2015-02-11 ⇒ 2015-06-18']", '[<a href="/teams/112-sk-gaming">SK Gaming</a>]': "['2012-01-13 ⇒ 2013-12-30']", '[<a href="/teams/133-old-generations">Old Generations</a>]': '[<span class="team_date_month_only">2010-08</span>, \' ⇒ 2012-01-13\']', '[<a href="/teams/143-mbcgame-hero">MBCGame HERO</a>]': "['2009-03-25 ⇒ 2010-08-24']"}}

In [231]:
j_df = pd.DataFrame(j)

In [363]:
j_df

,PlayerId,history
"[<a href=""/teams/112-sk-gaming"">SK Gaming</a>]",1000,['2012-01-13 ⇒ 2013-12-30']
"[<a href=""/teams/133-old-generations"">Old Generations</a>]",1000,"[<span class=""team_date_month_only"">2010-08</s..."
"[<a href=""/teams/141-cj-entus"">CJ Entus</a>]",1000,['2016-05-23 ⇒ 2016-10-18']
"[<a href=""/teams/143-mbcgame-hero"">MBCGame HERO</a>]",1000,['2009-03-25 ⇒ 2010-08-24']
"[<a href=""/teams/359-trig-esports"">Trig Esports</a>]",1000,['2015-02-11 ⇒ 2015-06-18']

In [375]:
j_df['team_name']=j_df.index

In [376]:
l = []
for i in j_df['team_name']:
    k = BeautifulSoup(i, 'lxml').a.text
    l.append(k)

j_df['team_name'] = l

In [322]:
a = j_df['history'][0]
a = a.split("⇒")

In [323]:
a = [x.strip("['], ") for x in a]

In [324]:
print(a[0],a[-1])

2012-01-13 2013-12-30

In [333]:
len(a[1])

10

In [414]:
from bs4 import BeautifulSoup
b = j_df['history'][1]

In [415]:
soup = BeautifulSoup(b, 'lxml')

In [418]:
for i in j_df['history']:
    print(i)

['2012-01-13 ⇒ 2013-12-30']
[<span class="team_date_month_only">2010-08</span>, ' ⇒ 2012-01-13']
['2016-05-23 ⇒ 2016-10-18']
['2009-03-25 ⇒ 2010-08-24']
['2015-02-11 ⇒ 2015-06-18']

In [328]:
b = j_df['history'][1]
b = b.split("⇒")

In [329]:
b = [x.strip("['], ") for x in b]

In [624]:
def parser(a):
    a = str(a).split("⇒")
    if len(a) == 1:
        soupy = BeautifulSoup(str(a).split(':')[0],'lxml')
        q = (soupy.p.text)
        j=[0,0]
        i = "[']"
        r = q.split(' ')[1].strip(i)
        j[0] = r[0:10]
        print(j[0])
        j[1] = np.datetime64('2020-10-10')
    else:
        a = [x.strip("['], ") for x in a]
        j = a
        for i in range(len(a)):
            if len(a[i])>10:
                soup = BeautifulSoup(a[i], 'lxml')
                k= soup.span.text
                if k == '<unknown>':
                    k = '2004-01-01'
                j[i] =k  
    j = [np.datetime64(x) for x in j]
    return j

In [587]:
soupy = BeautifulSoup(l_df['history'][0].split(':')[0],'lxml')
i = (soupy.p.text)
i.split(' ')[1].strip("']")

'2012-10-18'

In [625]:
for i in range(len(l_df)):
    print(parser(l_df['history'][i]))

2012-10-18
[numpy.datetime64('2012-10-18'), numpy.datetime64('2020-10-10')]

In [545]:
def compare_date_range(a, d):
    if (a > d[0]) & (a < d[1]):
        return True
    else:
        return False

In [543]:
def team_name_processing(dict, end_date):
    df = pd.DataFrame(dict)
    a = np.datetime64(end_date)
    for i in range(len(df)):
        b = df['history'][i]
        b = parser(b)
        if compare_date_range(a, b):
            return BeautifulSoup(df.index[i],'lxml').text
    return 'Unaffiliated'

In [627]:
print(team_name_processing(l,'2010-09-01'))

2012-10-18
Unaffiliated

In [565]:
l = {'PlayerId': 2798, 'history': {'[<a href="/teams/217-team-property">Team Property</a>]': "['Since 2012-10-18']"}}

In [566]:
l_df = pd.DataFrame(l)

In [567]:
l_df

,PlayerId,history
"[<a href=""/teams/217-team-property"">Team Property</a>]",2798,['Since 2012-10-18']

In [539]:
compare_date_range(a,b)

2010-08 2012-01-13

False

TypeError: '<' not supported between instances of 'str' and 'bool'

In [590]:
np.datetime64('2017-10-12')>np.datetime64('2017-01-01')

True